"""empty message

Revision ID: 8d0fee9ce0dd
Revises: 
Create Date: 2023-04-09 02:51:48.741615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d0fee9ce0dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=50), nullable=False),
    sa.Column('public_key_patient', sa.Integer(), nullable=False),
    sa.Column('public_key_doctor', sa.Integer(), nullable=False),
    sa.Column('key_frag', sa.LargeBinary(length=256), nullable=True),
    sa.Column('link', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    # ### end Alembic commands ###
