"""empty message

Revision ID: c6f48f3a4dfb
Revises: 23826012989e
Create Date: 2023-04-10 21:43:23.456735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6f48f3a4dfb'
down_revision = '23826012989e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=1024),
               existing_nullable=False)
        batch_op.alter_column('key_frag',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=1024),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.alter_column('key_frag',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=False)
        batch_op.alter_column('token',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
